name: Game CI Test Runner

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  workflow_dispatch:

jobs:
  runner:
    defaults:
      run:
        shell: bash
    name: Game CI's Test Runner
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: game-ci/unity-test-runner@v4
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
