on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  workflow_dispatch:

jobs:
  Runner:
    defaults:
      run:
        shell: bash
    name: Test Runner
    runs-on: windows-latest
    steps:
    - run: |
        echo "game-ci unity test runner"
        echo "==============================================="
        ls -la
        echo "==============================================="
        ls -la ..
        echo "==============================================="
        ls -la ~
        echo "==============================================="
        pwd

        
        git checkout origin/master
    - uses: game-ci/unity-test-runner@v4
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
    - run: echo "Hello world"
